# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "D:\\projetos\\GerenciadorDePedidos"
      dockerfile: "GerenciadorDePedidos.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/GerenciadorDePedidos.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "gerenciadordepedidos.api:dev"
    ports: []
    volumes:
    - "D:\\projetos\\GerenciadorDePedidos\\GerenciadorDePedidos.API:/app:rw"
    - "D:\\projetos\\GerenciadorDePedidos:/src:rw"
    - "C:\\Users\\suhet\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
