services:
  app:
    image: gerenciador-de-pedidos-api
    build:
      context: .  
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=GerenciadorDePedidos;User=root;Password=1234;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: GerenciadorDePedidos
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:                                  
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
        interval: 5s
        timeout: 5s
        retries: 10

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: