# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: NuGetToolInstaller@1

  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: '8.0.403'

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - script: dotnet build --configuration $(buildConfiguration) --no-restore
    displayName: 'Build the application'

  - script: dotnet test --no-build --configuration $(buildConfiguration)
    displayName: 'Run unit tests'

  - script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    
    displayName: 'Publish the application'

  - task: PublishPipelineArtifact@0
    displayName: 'Publish artifacts'
    inputs:
      ArtifactName: 'drop'
      targetPath: '$(Build.ArtifactStagingDirectory)'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure for Students(e44c7a8d-ddb9-4bde-bdfe-8a5e1e409c75)'
      appType: 'webApp'
      appName: 'gerenciadordepedidos'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
      deploymentMethod: 'auto'