services:
  api:
    build:
      context: ..
      dockerfile: GerenciadorDePedidos.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=GerenciadorDePedidos;User=banco_teste;Password=teste1234;
  
  db:
    image: mysql:latest
    environment:
      MYSQL_USER: banco_teste
      MYSQL_ROOT_PASSWORD: teste1234
      MYSQL_DATABASE: GerenciadorDePedidos
      MYSQL_PASSOWRD: teste1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      
volumes:
  db_data:

networks:
  app-network:
